# Generated by Django 5.2.17 on 2026-10-01 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='Nama lengkap')),
                ('faculty', models.CharField(blank=True, choices=[('FK', 'Fakultas Kedokteran'), ('FKG', 'Fakultas Kedokteran Gigi'), ('FMIPA', 'Fakultas Matematika dan Ilmu Pengetahuan Alam'), ('FT', 'Fakultas Teknik'), ('FH', 'Fakultas Hukum'), ('FEB', 'Fakultas Ekonomi dan Bisnis'), ('FIB', 'Fakultas Ilmu Pengetahuan Budaya'), ('FPSI', 'Fakultas Psikologi'), ('FISIP', 'Fakultas Ilmu Sosial dan Ilmu Politik'), ('FKM', 'Fakultas Kesehatan Masyarakat'), ('FASILKOM', 'Fakultas Ilmu Komputer'), ('FIK', 'Fakultas Ilmu Keperawatan'), ('FF', 'Fakultas Farmasi'), ('FIA', 'Fakultas Ilmu Administrasi'), ('VOKASI', 'Program Pendidikan Vokasi'), ('SIL', 'Sekolah Ilmu Lingkungan'), ('SKSG', 'Sekolah Kajian Stratejik dan Global')], max_length=10, verbose_name='Fakultas')),
                ('angkatan', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Angkatan')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
