# Generated by Django 5.2.17 on 2026-10-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='line_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID LINE'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_photos/', verbose_name='Foto profil'),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, verbose_name='Nomor WhatsApp'),
        ),
    ]
